---
_extends: template

repository:
  name: jvm-macros
  description: Various useful Scala macros
  topics: scala, macros
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - license/cla
